name: Agentspec CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-and-extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run linter
        run: |
          agentspec lint agentspec/

      - name: Extract agent specs
        run: |
          agentspec extract agentspec/ --json
        continue-on-error: true
